### ISSUE TITLE
TypeError: Cannot convert undefined or null to object     at Function.entries (<anonymous>)

### ISSUE THREAD

**Issue by RyanManchikanti** [ahmedbesbes/cartoonify#1]
TypeError: Cannot convert undefined or null to object

      at Function.entries (<anonymous>)

      at getConfigsByWarmer (C:\Users\ryan\OneDrive\Desktop\Cantoonify_Model\cartoonify\node_modules\serverless-plugin-warmup\src\config.js:170:34)

      at WarmUp.configPlugin (C:\Users\ryan\OneDrive\Desktop\Cantoonify_Model\cartoonify\node_modules\serverless-plugin-warmup\src\index.js:82:10)

      at C:\Users\ryan\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:501:55

      at tryCatcher (C:\Users\ryan\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\util.js:16:23)

      at Object.gotValue (C:\Users\ryan\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\reduce.js:168:18)

      at Object.gotAccum (C:\Users\ryan\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\reduce.js:155:25).

**Comment by RyanManchikanti** [comment]
This happens when deploying the serverless model.

**Comment by ahmedbesbes** [comment]
@RyanManchikanti 

Try not to use the warmup plugin and check if it works
