### ISSUE TITLE
Aws permission issue

### ISSUE THREAD

**Issue by ChinthanaW** [ahmedbesbes/cartoonify#5]
Lambda function fails when trying to load models from S3 with following output

```
[ERROR] ClientError: An error occurred (AccessDenied) when calling the GetObject operation: Access Denied
Traceback (most recent call last):
  File "/var/lang/lib/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/var/lang/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/task/src/handler.py", line 55, in <module>
    models = load_models(s3, bucket)
  File "/var/task/src/handler.py", line 39, in load_models
    response = s3.get_object(Bucket=bucket, Key=f"models/{style}_net_G_float.pth")
  File "/var/runtime/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
[ERROR] ClientError: An error occurred (AccessDenied) when calling the GetObject operation: Access Denied Traceback (most recent call last):   File "/var/lang/lib/python3.7/imp.py", line 234, in load_module     return load_source(name, filename, file)   File "/var/lang/lib/python3.7/imp.py", line 171, in load_source     module = _load(spec)   File "<frozen importlib._bootstrap>", line 696, in _load   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked   File "<frozen importlib._bootstrap_external>", line 728, in exec_module   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed   File "/var/task/src/handler.py", line 55, in <module>     models = load_models(s3, bucket)   File "/var/task/src/handler.py", line 39, in load_models     response = s3.get_object(Bucket=bucket, Key=f"models/{style}_net_G_float.pth")   File "/var/runtime/botocore/client.py", line 357, in _api_call     return self._make_api_call(operation_name, kwargs)   File "/var/runtime/botocore/client.py", line 676, in _make_api_call     raise error_class(parsed_response, operation_name) 
```

**Comment by ahmedbesbes** [comment]
Your need to create your own s3 bucket
